// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package adder

func Float32Add(x float32, y float32) float32 {
	return x + y
}

func Float64Add(x float64, y float64) float64 {
	return x + y
}

func IntAdd(x int, y int) int {
	return x + y
}

func Int16Add(x int16, y int16) int16 {
	return x + y
}

func Int32Add(x int32, y int32) int32 {
	return x + y
}

func Int64Add(x int64, y int64) int64 {
	return x + y
}

func Int8Add(x int8, y int8) int8 {
	return x + y
}

func UintAdd(x uint, y uint) uint {
	return x + y
}

func Uint16Add(x uint16, y uint16) uint16 {
	return x + y
}

func Uint32Add(x uint32, y uint32) uint32 {
	return x + y
}

func Uint64Add(x uint64, y uint64) uint64 {
	return x + y
}

func Uint8Add(x uint8, y uint8) uint8 {
	return x + y
}
