// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package adder

func Add(x float32, y float32) float32 {
	return x + y
}

func Add(x float64, y float64) float64 {
	return x + y
}

func Add(x int, y int) int {
	return x + y
}

func Add(x int16, y int16) int16 {
	return x + y
}

func Add(x int32, y int32) int32 {
	return x + y
}

func Add(x int64, y int64) int64 {
	return x + y
}

func Add(x int8, y int8) int8 {
	return x + y
}

func Add(x uint, y uint) uint {
	return x + y
}

func Add(x uint16, y uint16) uint16 {
	return x + y
}

func Add(x uint32, y uint32) uint32 {
	return x + y
}

func Add(x uint64, y uint64) uint64 {
	return x + y
}

func Add(x uint8, y uint8) uint8 {
	return x + y
}
